#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

# Assumes AWS CLI is installed. Updates an AWS Route53 DNS record.
# Usage: route53-update-record /hostedzone/FOOBARZONE foo.example.com 1.2.3.4

TMPFILE="$(mktemp)"

cleanup() {
    rm -f "$TMPFILE"
}

trap cleanup EXIT

if [[ "$#" -ne "3" ]]; then
    echo "ERROR: incorrect arguments provided" >&2
    exit 1
fi

if ! aws --version 2>/dev/null ; then
    echo "ERROR: AWS CLI tools are not installed" >&2
    exit 1
fi

HOSTED_ZONE_ID="$1"
DNS_RECORD_NAME="$2"
DNS_RECORD_VALUE="$3"

cat > "$TMPFILE" <<EOF
{
  "Comment": "Update DNS A Record for name $DNS_RECORD_NAME to IP $DNS_RECORD_VALUE",
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "$DNS_RECORD_NAME",
        "Type": "A",
        "TTL": 300,
        "ResourceRecords": [
          {
            "Value": "$DNS_RECORD_VALUE"
          }
        ]
      }
    }
  ]
}
EOF

echo "[*] Updating Route53 Record: $DNS_RECORD_NAME -> $DNS_RECORD_VALUE ..."
aws route53 change-resource-record-sets --hosted-zone-id="$HOSTED_ZONE_ID" --change-batch="file://$TMPFILE"
exit $?
